---
# TODO: common stuff
# - hosts: all
#   become: yes
#   tasks:
#     - import_role:
#         name: common-vps

- hosts: qwebirc
  become: yes
  tasks:
    - import_role:
        name: qwebirc

- hosts: icecast
  become: yes
  tasks:
    - import_role:
        name: icecast
      tags:
        - icecast

- hosts: webservers
  become: yes
  tasks:
    - import_role:
        name: nginx-keinfm
